const projects = [
  {
    name: "Project 1",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    status: "Completed",
    image: "img/p2.jpg",
    images: ["img/p2.jpg", "img/image3.jpg", "img/image0.jpg"],
    category: "Residential",
  },
  {
    name: "Project 2",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    status: "In Progress",
    image: "img/p1.jpg",
    images: ["https://via.placeholder.com/600x400"],
    category: "commercial",
  },
  {
    name: "Project 3",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    status: "Completed",
    image: "img/p3.jpg",
    images: ["https://via.placeholder.com/600x400"],
    category: "industrial",
  },
  {
    name: "Project 1",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    status: "Completed",
    image: "img/p2.jpg",
    images: ["img/p2.jpg", "img/image3.jpg", "img/image4.jpg"],
    category: "Residential",
  },
  {
    name: "Project 2",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    status: "In Progress",
    image: "img/p1.jpg",
    images: ["https://via.placeholder.com/600x400"],
    category: "commercial",
  },
  {
    name: "Project 3",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    status: "Completed",
    image: "img/p3.jpg",
    images: ["https://via.placeholder.com/600x400"],
    category: "industrial",
  },
  {
    name: "Project 1",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    status: "Completed",
    image: "img/p2.jpg",
    images: ["img/p2.jpg", "img/image3.jpg", "img/image4.jpg"],
    category: "Residential",
  },
  {
    name: "Project 2",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    status: "In Progress",
    image: "img/p1.jpg",
    images: ["https://via.placeholder.com/600x400"],
    category: "commercial",
  },
  {
    name: "Project 3",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    status: "Completed",
    image: "img/p3.jpg",
    images: ["https://via.placeholder.com/600x400"],
    category: "industrial",
  },
  {
    name: "Project 1",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    status: "Completed",
    image: "img/p2.jpg",
    images: ["img/p2.jpg", "img/image3.jpg", "img/image4.jpg"],
    category: "Residential",
  },
  {
    name: "Project 2",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    status: "In Progress",
    image: "img/p1.jpg",
    images: ["https://via.placeholder.com/600x400"],
    category: "commercial",
  },
  {
    name: "Project 3",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    status: "Completed",
    image: "img/p3.jpg",
    images: ["https://via.placeholder.com/600x400"],
    category: "industrial",
  },
];

export default projects;
